### ISSUE TITLE
Wrong ladder rank can be displayed

### ISSUE THREAD

**Issue by supersam710** [supersam710/HearthstoneDiscordRichPresence#1]
Occasionally impossible ranks such as "Platinum 11" will be displayed in place of their respective rank one level up ("Gold 1").

**Comment by supersam710** [comment]
Fixed in c09c784c8b99ba2df08ad8d64dbfd11b6e153930.

**Comment by samspillers** [comment]
Fixed in c09c784c8b99ba2df08ad8d64dbfd11b6e153930.
